name: Update elevators

# See if adding these permissions makes things work
permissions:
  contents: write
  pages: write
  id-token: write

on: 
  workflow_dispatch:
    inputs:
      elevator-left: 
        description: "Is the left elevator currently operational?"
        required: true
        type: boolean
      elevator-right:
        description: "Is the right elevator currently operational?" 
        required: true
        type: boolean

jobs:
  update-elevators:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt

      - run: echo "Left elevator working? ${{ inputs.elevator-left }}."
      - run: echo "Right elevator working? ${{inputs.elevator-right}}."

      - name: Run update_elevators
        run: python ./update_elevators.py ${{ inputs.elevator-left }} ${{ inputs.elevator-right }}

      - name: Commit elevator status update
        run: |
          git config --global user.name 'Vassily-Petrousevitch'
          git config --global user.email 'Vassily-Petrousevitch@users.noreply.github.com'
          git commit -am "Automated update"
          git push