name: Update elevators
on: 
  workflow_dispatch:
    inputs:
      elevator-left: 
        description: "Is the left elevator currently operational?"
        required: true
        type: boolean
      elevator-right:
        description: "Is the right elevator currently operational?" 
        required: true
        type: boolean

jobs:
  update-elevators:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - run: echo "Left elevator working? ${{ inputs.elevator-left }}."
      - run: echo "Right elevator working? ${{inputs.elevator-right}}."

      - name: Run update_elevators.js
        run: python ./update_elevators.py ${{ inputs.elevator-left }} ${{ inputs.elevator-right }}